import { Navbar } from "@/Layout/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Footer } from "@/Layout/Footer";
import { Provider } from "react-redux";

export const metadata: Metadata = {
  title: "Liquor Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
